# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: bankcheck
version: '0.0.0'
github: "githubuser/bankcheck"
license: MIT
author: "Leigh Perry"
maintainer: "Leigh Perry"
# synopsis: A new template package.
# description: bankcheck is a new template package.
# category: Other

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - cassava
  - text
  - vector
  - bytestring
  - parsec
  - transformers
  - MissingH
  - containers
  - regex-posix
  - mtl
  source-dirs: src

executables:
  bankcheck:
    source-dirs: app
    main: Main.hs
    dependencies:
    - base
    - bankcheck
    - optparse-applicative
    - transformers
    - mtl
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  bankcheck-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - bankcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  bankcheck-test-suite:
    source-dirs: test
    main: Main.hs
    dependencies:
    - base
    - bankcheck
    - hedgehog
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
